# -*- coding: utf-8 -*-
"""
/***************************************************************************
 CoronaCast
                                 A QGIS plugin
 This plugin opens a webpage showing the Corona CAST map in the clicked coordinates on the canvas
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-03-13
        copyright            : (C) 2024 by Ishiba RO
        email                : nimodo.nosepudosoloishiba@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load CoronaCast class from file CoronaCast.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .cast_corona_clicker import CoronaCast
    return CoronaCast(iface)
